/**
 * Header forensics and authentication correlation.
 *
 * Two jobs:
 *  1. Build the ordered `HeaderField[]` the Header Forensics page renders — the
 *     six core RFC 5322 fields plus whichever notable headers are present —
 *     flagging fields that are themselves evidence: a Reply-To on a different
 *     domain, a Return-Path that does not match the From, a display name that
 *     embeds a different address, an implausible Date, a missing Message-ID.
 *  2. Produce the `AuthenticationSummary` (SPF/DKIM/DMARC verdicts + alignment).
 *     Verdicts are always *evaluated here*, never taken from the backend's status
 *     strings: the backend reports whether a policy is published, not whether the
 *     connecting address is authorised by it. What the backend does contribute is
 *     live-DNS discovery of records the offline intelligence set does not cover,
 *     which is folded in as evaluator input. See `definitiveBackendVerdict`.
 */

import {
  evaluateSpf,
  evaluateDmarc,
  isAligned,
  parseDkimSignature,
  parseDmarcRecord,
  definitiveBackendVerdict,
  firstRecord,
} from '@/lib/authEval';
import { addressOf, domainOf } from '@/lib/format';
import type { ParsedEmail } from '@/lib/emailParser';
import { header } from '@/lib/emailParser';
import type {
  AuthVerdict,
  AuthenticationCheck,
  AuthenticationSummary,
  DataOrigin,
  EmailMetadata,
  HeaderField,
  Severity,
} from '@/types';
import type { WireForensics } from '../wire';
import type { DomainRecord } from '../intel/domainDatabase';
import { NOT_PRESENT, escalate, orgOf, sameOrganisation } from './shared';

export interface HeaderAnomaly {
  name: string;
  severity: Severity;
  reason: string;
}

interface HeaderForensics {
  headers: HeaderField[];
  anomalies: HeaderAnomaly[];
}

/**
 * Headers beyond the core six that carry forensic weight when present, in
 * display order. Each is rendered only if the message actually contains it, so
 * the table never shows empty rows.
 */
const NOTABLE_HEADERS = [
  'Sender',
  'X-Original-Sender',
  'Authentication-Results',
  'Received-SPF',
  'X-Originating-IP',
  'X-Sender-IP',
  'X-Forwarded-For',
  'X-Mailer',
  'User-Agent',
  'X-Priority',
  'Importance',
  'X-Spam-Status',
  'X-Spam-Score',
  'List-Unsubscribe',
  'MIME-Version',
  'Content-Type',
];

/**
 * Mailer signatures that indicate the message was generated by a script rather
 * than a mail client or a managed platform. Legitimate bulk mail uses these too,
 * so this is corroborating context, not proof of anything on its own.
 */
const SCRIPTED_MAILER = /phpmailer|php-?mail|x-?php|python|perl|libcurl|curl\/|sendmail\s|mass\s*mail|bulk\s*mail|swiftmailer/i;

/**
 * Build the header table. `metadata` carries the recovered fields (Reply-To and
 * Return-Path come from the local parser, which the backend does not return).
 * `analyzedAt` anchors the Date plausibility check; `parsed` supplies the
 * notable-header rows.
 */
export function buildHeaderForensics(
  metadata: EmailMetadata,
  analyzedAt: string,
  parsed?: ParsedEmail,
): HeaderForensics {
  const anomalies: HeaderAnomaly[] = [];
  const fromDomain = domainOf(metadata.from);

  const fields: { name: string; value: string; anomaly?: HeaderAnomaly }[] = [
    { name: 'From', value: metadata.from || NOT_PRESENT },
    { name: 'Return-Path', value: metadata.returnPath ?? NOT_PRESENT },
    { name: 'Reply-To', value: metadata.replyTo ?? NOT_PRESENT },
    { name: 'To', value: metadata.to || NOT_PRESENT },
    { name: 'Subject', value: metadata.subject || NOT_PRESENT },
    { name: 'Date', value: metadata.date ?? NOT_PRESENT },
    { name: 'Message-ID', value: metadata.messageId ?? NOT_PRESENT },
  ];

  const record = (name: string, anomaly: HeaderAnomaly): void => {
    anomalies.push(anomaly);
    attach(fields, name, anomaly);
  };

  // A message with no usable From header cannot be attributed at all, and no
  // domain-based check below can run.
  if (!fromDomain) {
    record('From', {
      name: 'From',
      severity: 'HIGH',
      reason: metadata.from
        ? `The From header (${metadata.from}) contains no parseable domain, so the sender cannot be attributed or authenticated.`
        : 'No From header is present, so the message has no claimed sender to authenticate.',
    });
  }

  // A display name that embeds its own address is a direct spoofing attempt: the
  // recipient reads the address in the name and never sees the real one.
  const embedded = metadata.fromDisplayName?.match(/[\w.+-]+@[\w.-]+\.\w+/)?.[0]?.toLowerCase() ?? null;
  if (embedded && embedded !== addressOf(metadata.from).toLowerCase()) {
    record('From', {
      name: 'From',
      severity: 'HIGH',
      reason: `The display name embeds the address ${embedded}, but the message was actually sent by ${addressOf(metadata.from) || 'an unparseable address'}. Mail clients show the display name, so the recipient sees the embedded address instead of the real one.`,
    });
  }

  // Reply-To on a different organisation is a hallmark of BEC: the reply is
  // steered to attacker-controlled infrastructure while the From looks familiar.
  if (metadata.replyTo) {
    const replyDomain = domainOf(metadata.replyTo);
    if (replyDomain && fromDomain && !sameOrganisation(replyDomain, fromDomain)) {
      record('Reply-To', {
        name: 'Reply-To',
        severity: 'HIGH',
        reason: `Reply-To (${replyDomain}) resolves to a different organisation than From (${fromDomain}); replies would leave the apparent sender's domain.`,
      });
    }
  }

  // Return-Path (envelope sender) mismatch weakens SPF alignment and often
  // reveals the real sending infrastructure behind a spoofed From.
  if (metadata.returnPath) {
    const rpDomain = domainOf(metadata.returnPath);
    if (rpDomain && fromDomain && !sameOrganisation(rpDomain, fromDomain)) {
      record('Return-Path', {
        name: 'Return-Path',
        severity: 'MEDIUM',
        reason: `Envelope Return-Path (${rpDomain}) does not align with the visible From domain (${fromDomain}).`,
      });
    }
  }

  // Message-ID domain mismatch is a weaker signal but corroborates the others.
  if (metadata.messageId) {
    const midHost = metadata.messageId.match(/@([^>]+)>?/)?.[1]?.toLowerCase() ?? null;
    if (midHost && fromDomain && orgOf(midHost) && !sameOrganisation(midHost, fromDomain)) {
      record('Message-ID', {
        name: 'Message-ID',
        severity: 'LOW',
        reason: `Message-ID was issued by ${midHost}, which differs from the sender domain ${fromDomain}.`,
      });
    }
  } else {
    record('Message-ID', {
      name: 'Message-ID',
      severity: 'LOW',
      reason: 'No Message-ID header is present; legitimate MTAs almost always add one.',
    });
  }

  // Date plausibility. A timestamp ahead of acquisition means the sender's clock
  // was wrong or the header was forged; either way the chronology is unreliable.
  if (!metadata.date) {
    record('Date', {
      name: 'Date',
      severity: 'LOW',
      reason: 'No Date header is present, so the message cannot be placed on a timeline from its own metadata.',
    });
  } else {
    const sent = new Date(metadata.date).getTime();
    const received = new Date(analyzedAt).getTime();
    if (Number.isNaN(sent)) {
      record('Date', {
        name: 'Date',
        severity: 'LOW',
        reason: `The Date header (${metadata.date}) is not a valid RFC 5322 timestamp, which is unusual for mail produced by a standard client.`,
      });
    } else if (!Number.isNaN(received) && sent - received > 86_400_000) {
      record('Date', {
        name: 'Date',
        severity: 'MEDIUM',
        reason: `The Date header claims the message was sent more than a day after it was acquired for analysis, so the stated send time is not credible.`,
      });
    }
  }

  if (!metadata.subject) {
    record('Subject', {
      name: 'Subject',
      severity: 'INFO',
      reason: 'The message has no Subject header.',
    });
  }

  const notable = parsed ? collectNotableHeaders(parsed, fromDomain, anomalies) : [];

  const headers: HeaderField[] = [...fields, ...notable].map((field) =>
    field.anomaly
      ? { name: field.name, value: field.value, anomaly: { severity: field.anomaly.severity, reason: field.anomaly.reason } }
      : { name: field.name, value: field.value },
  );

  return { headers, anomalies };
}

/**
 * Rows for the notable headers actually present, flagging the two cases that are
 * themselves evidence: an envelope `Sender` on unrelated infrastructure, and a
 * scripted mailer signature.
 */
function collectNotableHeaders(
  parsed: ParsedEmail,
  fromDomain: string,
  anomalies: HeaderAnomaly[],
): { name: string; value: string; anomaly?: HeaderAnomaly }[] {
  const rows: { name: string; value: string; anomaly?: HeaderAnomaly }[] = [];

  for (const name of NOTABLE_HEADERS) {
    const value = header(parsed, name.toLowerCase());
    if (!value) continue;

    let anomaly: HeaderAnomaly | undefined;

    if (name === 'Sender' || name === 'X-Original-Sender') {
      const senderDomain = domainOf(value);
      if (senderDomain && fromDomain && !sameOrganisation(senderDomain, fromDomain)) {
        anomaly = {
          name,
          severity: 'MEDIUM',
          reason: `${name} names ${senderDomain}, which is a different organisation to the From domain (${fromDomain}). The message was submitted by infrastructure other than the apparent sender's.`,
        };
      }
    }

    if ((name === 'X-Mailer' || name === 'User-Agent') && SCRIPTED_MAILER.test(value)) {
      anomaly = {
        name,
        severity: 'MEDIUM',
        reason: `${name} reports "${value}", indicating the message was generated by a script rather than a mail client. Legitimate bulk mail also does this, so treat it as corroboration alongside the other findings.`,
      };
    }

    if (anomaly) anomalies.push(anomaly);
    rows.push(anomaly ? { name, value, anomaly } : { name, value });
  }

  return rows;
}

/**
 * Attach an anomaly to its row. A single row can attract more than one finding
 * (a From header can be both unparseable and carry a spoofed display name), and
 * the row can only show one, so the more severe wins.
 */
function attach(
  fields: { name: string; anomaly?: HeaderAnomaly }[],
  name: string,
  anomaly: HeaderAnomaly,
): void {
  const field = fields.find((entry) => entry.name === name);
  if (!field) return;
  if (!field.anomaly || escalate(field.anomaly.severity, anomaly.severity) === anomaly.severity) {
    field.anomaly = anomaly;
  }
}

/* ------------------------------------------------------------------ */
/* Authentication                                                      */
/* ------------------------------------------------------------------ */

export interface AuthenticationResult {
  summary: AuthenticationSummary;
  spf: AuthVerdict;
  dkim: AuthVerdict;
  dmarc: AuthVerdict;
  spfAligned: boolean | null;
  dkimAligned: boolean | null;
  dmarcEnforced: boolean;
}

/** Where the policy that was actually evaluated came from. */
type PolicySource = 'CURATED' | 'LIVE_DNS' | 'UNRESOLVED';

/**
 * The only DKIM verdicts reachable without a DNS key lookup. PASS is deliberately
 * excluded: confirming a signature requires retrieving the public key and
 * recomputing the body hash, neither of which is possible offline, so the type
 * makes it impossible to report a DKIM pass we did not actually verify.
 */
type DkimStructuralVerdict = 'NONE' | 'FAIL' | 'NEUTRAL';

/**
 * Correlate authentication. `wireForensics` is the backend's result when the
 * live service answered; `senderDomainRecord` is the curated sender policy.
 *
 * Every verdict is evaluated in this function. The backend contributes exactly
 * two things: records it discovered via live DNS (evaluator input for domains the
 * offline set does not cover), and the few statuses that are genuinely conclusive.
 * It is never used as a verdict, because `status: "pass"` from the backend means
 * "a record is published", not "this message authenticated".
 *
 * `observedIp` must be the *boundary* address — the host that connected to the
 * recipient's mail server — not the origin address reported by the geolocation
 * view. A message relayed through an intermediate host fails SPF at the boundary
 * even when its origin sits inside the sender's own published range, so
 * evaluating SPF against the origin silently inverts the result.
 */
export function correlateAuthentication(params: {
  fromDomain: string;
  dkimSignature: string;
  returnPathDomain: string | null;
  senderDomainRecord: DomainRecord | null;
  observedIp: string | null;
  wireForensics: WireForensics | null;
  /**
   * Which engine produced `wireForensics`. Needed because in simulated mode the
   * wire's `records` arrays come from the same offline set as
   * `senderDomainRecord`, so a record arriving via the wire is only genuinely
   * live-resolved when a real backend answered.
   */
  origin: DataOrigin;
}): AuthenticationResult {
  const { fromDomain, dkimSignature, returnPathDomain, senderDomainRecord, observedIp, wireForensics, origin } = params;

  const backendAuth = wireForensics?.authentication;
  const dkimTags = parseDkimSignature(dkimSignature);

  // DKIM is settled entirely locally. The backend does not verify the body hash,
  // so it knows nothing here the parser does not, and its `domain_mismatch` test
  // is an exact string compare that misreports legitimate subdomain signing.
  // No signature is NONE; a signature whose `d=` domain does not align with the
  // From domain is a FAIL (an attacker can only sign for infrastructure they
  // control); an aligned signature is NEUTRAL, because offline evaluation cannot
  // retrieve the public key to verify the cryptographic body hash.
  const dkimVerdict: DkimStructuralVerdict = !dkimSignature
    ? 'NONE'
    : dkimTags.domain && !sameOrganisation(dkimTags.domain, fromDomain)
      ? 'FAIL'
      : 'NEUTRAL';

  // SPF authenticates the envelope sender (Return-Path). When it is absent we
  // fall back to the header From domain so alignment stays defined. An empty
  // string (a malformed Return-Path) is treated as absent.
  const spfIdentityDomain = returnPathDomain || fromDomain;

  const backendSpfRecord = firstRecord(backendAuth?.spf?.records);
  const spfRecord = senderDomainRecord?.spfRecord ?? backendSpfRecord;
  const spfEval = evaluateSpf(spfRecord, observedIp);
  const spfVerdict = resolveVerdict(
    spfEval.verdict,
    spfRecord,
    definitiveBackendVerdict(backendAuth?.spf?.status),
  );

  // DMARC is evaluated against the two verdicts settled above, so its stated
  // reasoning always matches what the other rows report.
  const backendDmarcRecord = firstRecord(backendAuth?.dmarc?.records);
  const dmarcRecord = senderDomainRecord?.dmarcRecord ?? backendDmarcRecord;
  const dmarcEval = evaluateDmarc({
    record: dmarcRecord,
    fromDomain,
    spfVerdict,
    spfDomain: spfIdentityDomain,
    dkimVerdict,
    dkimDomain: dkimTags.domain,
  });
  const dmarcVerdict = resolveVerdict(
    dmarcEval.verdict,
    dmarcRecord,
    definitiveBackendVerdict(backendAuth?.dmarc?.status),
  );

  // SPF alignment compares the authenticated envelope domain with the visible
  // From domain — a pass for unrelated infrastructure does not authenticate the
  // brand the recipient sees.
  const spfAligned = spfVerdict === 'PASS' ? isAligned(spfIdentityDomain, fromDomain) : false;
  const dkimAligned = dkimTags.domain ? isAligned(dkimTags.domain, fromDomain) : null;
  // A published policy of quarantine or reject means the domain owner asked
  // receivers to act on failures. Parse the record so `p=reject` is not matched
  // inside an `sp=reject` subdomain directive.
  const dmarcTags = parseDmarcRecord(dmarcRecord);
  const dmarcEnforced = dmarcTags?.policy === 'reject' || dmarcTags?.policy === 'quarantine';

  const spfSource = policySource(senderDomainRecord?.spfRecord ?? null, backendSpfRecord, origin);
  const dmarcSource = policySource(senderDomainRecord?.dmarcRecord ?? null, backendDmarcRecord, origin);

  const checks: AuthenticationCheck[] = [
    {
      mechanism: 'SPF',
      verdict: spfVerdict,
      aligned: spfVerdict === 'PASS' ? spfAligned : null,
      detail: withSource(spfEval.explanation, spfSource, 'SPF'),
      ...(spfRecord ? { raw: spfRecord } : {}),
    },
    {
      mechanism: 'DKIM',
      verdict: dkimVerdict,
      aligned: dkimAligned,
      detail: dkimDetail(dkimVerdict, dkimTags.domain, fromDomain),
      ...(dkimSignature ? { raw: truncateSignature(dkimSignature) } : {}),
    },
    {
      mechanism: 'DMARC',
      verdict: dmarcVerdict,
      aligned: eitherAligned(dmarcEval.spfAligned, dmarcEval.dkimAligned),
      detail: withSource(dmarcEval.explanation, dmarcSource, 'DMARC'),
      ...(dmarcRecord ? { raw: dmarcRecord } : {}),
    },
  ];

  return {
    summary: {
      senderDomain: fromDomain,
      checks,
      // Derived from the evaluated verdicts, not from the backend's
      // `overall_trust_score`: that figure adds points for SPF and DMARC records
      // merely existing, so a message failing all three checks scores highly.
      trustScore: verdictTrustScore(spfVerdict, dkimVerdict, dmarcVerdict),
      alignmentNote: alignmentNote(spfVerdict, dkimVerdict, dmarcVerdict, spfAligned, dkimAligned),
    },
    spf: spfVerdict,
    dkim: dkimVerdict,
    dmarc: dmarcVerdict,
    spfAligned,
    dkimAligned,
    dmarcEnforced,
  };
}

/**
 * Decide how to describe the provenance of the record that was evaluated.
 *
 * A record reaching us through the wire counts as live DNS only when a real
 * backend produced that wire. In simulated mode the local engine populates the
 * same `records` arrays from the offline intelligence set, and labelling those as
 * live-resolved would misrepresent the evidence.
 */
function policySource(curated: string | null, discovered: string | null, origin: DataOrigin): PolicySource {
  if (curated) return 'CURATED';
  if (!discovered) return 'UNRESOLVED';
  return origin === 'LIVE_BACKEND' ? 'LIVE_DNS' : 'CURATED';
}

/**
 * Say where the evaluated policy came from. An investigator reading a verdict has
 * to know whether the record behind it was resolved from live DNS or read from the
 * offline intelligence set, because only one of those is current.
 */
function withSource(explanation: string, source: PolicySource, mechanism: string): string {
  if (source === 'LIVE_DNS') {
    return `${explanation} The ${mechanism} record was resolved from live DNS by the analysis service.`;
  }
  if (source === 'CURATED') {
    return `${explanation} The ${mechanism} record came from the offline intelligence set; confirm it against live DNS before relying on this in a filing.`;
  }
  return explanation;
}

/**
 * Combine the local evaluation with whatever the backend definitively established.
 *
 * The local evaluator wins whenever a policy was actually available to evaluate,
 * because it is the only side that matched the connecting address against the
 * mechanisms and tested identifier alignment. The backend decides only when there
 * was nothing to evaluate: it can confirm an absence, or report that its lookup
 * failed — materially different from "no policy is published", which is why that
 * distinction is preserved rather than flattened to NONE.
 */
function resolveVerdict(
  local: AuthVerdict,
  record: string | null,
  backend: AuthVerdict | null,
): AuthVerdict {
  if (record) return local;
  return backend ?? local;
}

/**
 * Three-valued OR over alignment results. DMARC passes if *either* identifier
 * aligns, so a confirmed alignment (`true`) wins; otherwise a confirmed
 * non-alignment (`false`) is reported; only when both are unknown is the result
 * `null`. A plain `a || b` would collapse `false || null` to `null` and hide a
 * known misalignment.
 */
function eitherAligned(a: boolean | null, b: boolean | null): boolean | null {
  if (a === true || b === true) return true;
  if (a === false || b === false) return false;
  return null;
}

/**
 * Explain a DKIM verdict. The parameter is the narrow structural union rather than
 * `AuthVerdict`, which makes the three cases exhaustive: without the public key
 * there is no route to PASS or ERROR here, so branches for those would be
 * unreachable text that reads as if the signature had been cryptographically
 * verified.
 */
function dkimDetail(verdict: DkimStructuralVerdict, dkimDomain: string | null, fromDomain: string): string {
  switch (verdict) {
    case 'NONE':
      return 'The message carries no DKIM signature, so its content and sender cannot be cryptographically verified.';
    case 'FAIL':
      return `The DKIM signature was issued for ${dkimDomain ?? 'a different domain'}, which does not align with the sender domain ${fromDomain} — a signature the attacker controls does not authenticate the impersonated brand.`;
    case 'NEUTRAL':
      return `The message is DKIM-signed for ${dkimDomain ?? fromDomain} and that domain aligns with the From header. Offline evaluation cannot retrieve the public key to verify the body hash, so this reflects signature presence and alignment only, not a verified signature.`;
  }
}

function alignmentNote(
  spf: AuthVerdict,
  dkim: AuthVerdict,
  dmarc: AuthVerdict,
  spfAligned: boolean | null,
  dkimAligned: boolean | null,
): string {
  if (dmarc === 'PASS') return 'At least one authenticated identifier aligns with the visible From domain; DMARC passes.';
  if (spf === 'FAIL' && dkim !== 'PASS') {
    return 'Neither SPF nor DKIM produced an aligned pass, so a DMARC-enforcing receiver would not treat this message as authentic.';
  }
  if (spfAligned === false && dkimAligned === false) {
    return 'No identifier aligns with the From domain — the authenticated identity, where present, belongs to different infrastructure.';
  }
  return 'Authentication is inconclusive: some identifiers could not be resolved offline. Corroborate against live DNS before relying on the result.';
}

/**
 * How much the receiving infrastructure should trust this sender, 0–100, derived
 * from the three evaluated verdicts.
 *
 * Deliberately not the backend's `overall_trust_score`, which awards points for
 * SPF and DMARC records merely being *published* — so a spoofed message
 * impersonating a well-configured brand scores higher than one impersonating a
 * domain with no policy at all, exactly inverting the signal.
 *
 * 50 is the neutral starting point: an unauthenticated message is not yet
 * evidence of anything. DKIM carries the largest positive weight because it is
 * cryptographic and survives forwarding, while SPF carries the largest negative
 * weight because a FAIL is an explicit statement by the domain owner that this
 * host is not permitted to send for them.
 */
function verdictTrustScore(spf: AuthVerdict, dkim: AuthVerdict, dmarc: AuthVerdict): number {
  let score = 50;
  if (spf === 'PASS') score += 15;
  else if (spf === 'FAIL') score -= 20;
  else if (spf === 'SOFTFAIL') score -= 10;
  if (dkim === 'PASS') score += 20;
  else if (dkim === 'FAIL') score -= 15;
  if (dmarc === 'PASS') score += 15;
  else if (dmarc === 'FAIL') score -= 15;
  return Math.max(0, Math.min(100, score));
}

function truncateSignature(signature: string): string {
  return signature.length > 180 ? `${signature.slice(0, 180)}…` : signature;
}

/** Fold authentication verdicts into the header anomaly stream for scoring. */
export function authAnomalies(result: AuthenticationResult): HeaderAnomaly[] {
  const anomalies: HeaderAnomaly[] = [];

  if (result.spf === 'FAIL') {
    anomalies.push({
      name: 'SPF',
      severity: 'HIGH',
      reason: 'SPF evaluates to FAIL: the sending address is not authorised by the sender domain policy.',
    });
  } else if (result.spf === 'SOFTFAIL') {
    anomalies.push({
      name: 'SPF',
      severity: 'MEDIUM',
      reason: 'SPF soft-fails: the sender domain lists this address as probably unauthorised.',
    });
  } else if (result.spf === 'NONE') {
    anomalies.push({
      name: 'SPF',
      severity: 'LOW',
      reason: 'The sender domain publishes no SPF policy, so unauthorised senders cannot be ruled out.',
    });
  } else if (result.spf === 'PASS' && result.spfAligned === false) {
    anomalies.push({
      name: 'SPF',
      severity: 'MEDIUM',
      reason: 'SPF passed for the envelope domain but that domain does not align with the visible From address.',
    });
  }

  if (result.dkim === 'FAIL') {
    anomalies.push({
      name: 'DKIM',
      severity: 'HIGH',
      reason: 'The DKIM signature domain does not align with the sender domain, so the signature authenticates unrelated infrastructure.',
    });
  } else if (result.dkim === 'NONE') {
    anomalies.push({
      name: 'DKIM',
      severity: 'MEDIUM',
      reason: 'The message is unsigned, so neither its integrity nor its origin can be verified.',
    });
  }

  if (result.dmarc === 'FAIL') {
    anomalies.push({
      name: 'DMARC',
      severity: 'HIGH',
      reason: 'DMARC fails: no aligned, authenticated identifier exists for the visible From domain.',
    });
  } else if (result.dmarc === 'NONE') {
    anomalies.push({
      name: 'DMARC',
      severity: 'MEDIUM',
      reason: 'No DMARC policy is published, so receivers have no instruction to reject spoofed mail for this domain.',
    });
  } else if (result.dmarc === 'PASS' && !result.dmarcEnforced) {
    anomalies.push({
      name: 'DMARC',
      severity: 'LOW',
      reason: 'DMARC passes but the published policy is p=none, so failures elsewhere would still be delivered.',
    });
  }

  return anomalies;
}
