import type {
  AuthVerdict,
  Capability,
  HopTrust,
  IocType,
  Reputation,
  Role,
  Severity,
} from '@/types';

/* ------------------------------------------------------------------ */
/* Brand                                                               */
/* ------------------------------------------------------------------ */

export const BRAND = {
  name: 'SENTINELTRACE',
  tagline: 'AI FORENSIC INTELLIGENCE PLATFORM',
  subtitle: 'AI-Powered Email Threat Detection & Forensic Intelligence',
  problemStatement: 'SIH 26106',
} as const;

/**
 * Shown wherever the platform reports a geographic or origin estimate.
 * Non-negotiable: the product supports attribution, it does not perform it.
 */
export const ATTRIBUTION_DISCLAIMER =
  'Geolocation reflects the probable location of observed network infrastructure. It does not establish the physical location or identity of any individual and must be treated as an investigative lead only.';

export const EVIDENCE_DISCLAIMER =
  'Findings are generated by automated analysis and require analyst corroboration before use in any formal proceeding.';

/* ------------------------------------------------------------------ */
/* Severity presentation                                               */
/* ------------------------------------------------------------------ */

export interface SeverityStyle {
  label: string;
  text: string;
  bg: string;
  border: string;
  ring: string;
  /** Raw hex for SVG/chart fills, which cannot use Tailwind classes. */
  hex: string;
}

export const SEVERITY_STYLES: Record<Severity, SeverityStyle> = {
  CRITICAL: {
    label: 'Critical',
    text: 'text-critical',
    bg: 'bg-critical/10',
    border: 'border-critical/40',
    ring: 'ring-critical/30',
    hex: '#FF3B52',
  },
  HIGH: {
    label: 'High',
    text: 'text-high',
    bg: 'bg-high/10',
    border: 'border-high/40',
    ring: 'ring-high/30',
    hex: '#FF7A3D',
  },
  MEDIUM: {
    label: 'Medium',
    text: 'text-medium',
    bg: 'bg-medium/10',
    border: 'border-medium/40',
    ring: 'ring-medium/30',
    hex: '#F5B133',
  },
  LOW: {
    label: 'Low',
    text: 'text-low',
    bg: 'bg-low/10',
    border: 'border-low/40',
    ring: 'ring-low/30',
    hex: '#38BDF8',
  },
  INFO: {
    label: 'Info',
    text: 'text-ink-dim',
    bg: 'bg-ink/5',
    border: 'border-edge-strong',
    ring: 'ring-edge-strong',
    hex: '#98A4BA',
  },
};

export const AUTH_STYLES: Record<AuthVerdict, { text: string; bg: string; border: string }> = {
  PASS: { text: 'text-safe', bg: 'bg-safe/10', border: 'border-safe/40' },
  FAIL: { text: 'text-critical', bg: 'bg-critical/10', border: 'border-critical/40' },
  SOFTFAIL: { text: 'text-medium', bg: 'bg-medium/10', border: 'border-medium/40' },
  NEUTRAL: { text: 'text-ink-dim', bg: 'bg-ink/5', border: 'border-edge-strong' },
  NONE: { text: 'text-high', bg: 'bg-high/10', border: 'border-high/40' },
  ERROR: { text: 'text-ink-faint', bg: 'bg-ink/5', border: 'border-edge-strong' },
};

export const REPUTATION_STYLES: Record<Reputation, { label: string; text: string; bg: string }> = {
  MALICIOUS: { label: 'Malicious', text: 'text-critical', bg: 'bg-critical/10' },
  SUSPICIOUS: { label: 'Suspicious', text: 'text-high', bg: 'bg-high/10' },
  UNKNOWN: { label: 'Unknown', text: 'text-ink-dim', bg: 'bg-ink/5' },
  CLEAN: { label: 'Clean', text: 'text-safe', bg: 'bg-safe/10' },
};

export const HOP_TRUST_STYLES: Record<
  HopTrust,
  { label: string; text: string; border: string; dot: string; hex: string }
> = {
  TRUSTED: {
    label: 'Trusted hop',
    text: 'text-safe',
    border: 'border-safe/45',
    dot: 'bg-safe',
    hex: '#2DD4A7',
  },
  SUSPICIOUS: {
    label: 'Suspicious hop',
    text: 'text-critical',
    border: 'border-critical/45',
    dot: 'bg-critical',
    hex: '#FF3B52',
  },
  UNKNOWN: {
    label: 'Unknown hop',
    text: 'text-medium',
    border: 'border-medium/45',
    dot: 'bg-medium',
    hex: '#F5B133',
  },
};

export const IOC_TYPE_LABELS: Record<IocType, string> = {
  IP: 'IP Address',
  DOMAIN: 'Domain',
  URL: 'URL',
  EMAIL: 'Email Address',
  HASH: 'File Hash',
  ATTACHMENT: 'Attachment',
  MESSAGE_ID: 'Message-ID',
};

/* ------------------------------------------------------------------ */
/* Roles & capabilities                                                */
/* ------------------------------------------------------------------ */

export const ROLE_LABELS: Record<Role, string> = {
  ADMIN: 'Administrator',
  SOC_ANALYST: 'SOC Analyst',
  INVESTIGATOR: 'Investigator',
  AUDITOR: 'Auditor',
};

export const ROLE_DESCRIPTIONS: Record<Role, string> = {
  ADMIN: 'Full platform control including retention policy and user administration.',
  SOC_ANALYST: 'Triage and analyse email, raise alerts, and escalate into cases.',
  INVESTIGATOR: 'Own cases end to end, manage evidence, and export forensic reports.',
  AUDITOR: 'Read-only access to findings, audit trail, and chain of custody.',
};

/**
 * Capability grants per role. The auditor is deliberately read-only: it can see
 * everything relevant to oversight but mutate nothing.
 */
export const ROLE_CAPABILITIES: Record<Role, Capability[]> = {
  ADMIN: [
    'analyze:email',
    'view:forensics',
    'view:intel',
    'manage:cases',
    'manage:alerts',
    'export:report',
    'view:audit',
    'manage:settings',
  ],
  SOC_ANALYST: [
    'analyze:email',
    'view:forensics',
    'view:intel',
    'manage:alerts',
    'export:report',
  ],
  INVESTIGATOR: [
    'analyze:email',
    'view:forensics',
    'view:intel',
    'manage:cases',
    'manage:alerts',
    'export:report',
  ],
  AUDITOR: ['view:forensics', 'view:intel', 'view:audit'],
};

export function roleHas(role: Role, capability: Capability): boolean {
  return ROLE_CAPABILITIES[role].includes(capability);
}

/* ------------------------------------------------------------------ */
/* Time ranges                                                         */
/* ------------------------------------------------------------------ */

export const TIME_RANGE_OPTIONS = [
  { value: '24H', label: 'Today' },
  { value: '7D', label: '7 Days' },
  { value: '30D', label: '30 Days' },
  { value: '90D', label: '90 Days' },
] as const;

export const TIME_RANGE_DAYS: Record<string, number> = {
  '24H': 1,
  '7D': 7,
  '30D': 30,
  '90D': 90,
};

/* ------------------------------------------------------------------ */
/* Chart palette                                                       */
/* ------------------------------------------------------------------ */

export const CHART_COLORS = {
  intel: '#22D3EE',
  azure: '#3B82F6',
  critical: '#FF3B52',
  high: '#FF7A3D',
  medium: '#F5B133',
  safe: '#2DD4A7',
  violet: '#A78BFA',
  grid: 'rgba(148,163,184,0.10)',
  axis: '#66718A',
  tooltipBg: '#0E1524',
} as const;

export const CHART_SERIES = [
  CHART_COLORS.critical,
  CHART_COLORS.high,
  CHART_COLORS.medium,
  CHART_COLORS.intel,
  CHART_COLORS.azure,
  CHART_COLORS.violet,
  CHART_COLORS.safe,
];
