import React from 'react';
import {
  Shield, CheckCircle2, AlertTriangle, HelpCircle, Info, Sparkles,
  Layers, Lock, Database, ArrowRight
} from 'lucide-react';
import type { EmailAnalysis } from '@/types';

interface EvidenceConfidenceProps {
  analysis: EmailAnalysis;
}

export function EvidenceConfidence({ analysis }: EvidenceConfidenceProps) {
  const { score, assessment, originAssessment, authentication, domainIntel, urls, attachments } = analysis;

  // Real facts derived from evidence
  const facts = [
    {
      label: 'Cryptographic Digest',
      value: `SHA-256: ${analysis.evidence.sha256.slice(0, 24)}...`,
      type: 'IMMUTABLE_HASH',
    },
    {
      label: 'Observed Relay IP',
      value: originAssessment.observedSourceIp || 'Not Determined',
      type: 'NETWORK_SOCKET',
    },
    {
      label: 'MIME From / Return-Path',
      value: `${analysis.metadata.from} (Return-Path: ${analysis.metadata.returnPath || 'N/A'})`,
      type: 'HEADER_FIELD',
    },
    {
      label: 'RFC Authentication Outcomes',
      value: `SPF: ${authentication.checks.find(c => c.mechanism === 'SPF')?.verdict || 'NONE'}, DKIM: ${authentication.checks.find(c => c.mechanism === 'DKIM')?.verdict || 'NONE'}, DMARC: ${authentication.checks.find(c => c.mechanism === 'DMARC')?.verdict || 'NONE'}`,
      type: 'DNS_EVALUATION',
    },
  ];

  // Observations made from verified telemetry
  const observations = [
    {
      label: 'Infrastructure Geolocation',
      value: `IP geolocates to ${originAssessment.estimatedLocation?.country || 'Unknown'} (${originAssessment.estimatedLocation?.city || 'Unknown City'}).`,
      detail: 'Resolved via MaxMind GeoIP telemetry for observed MTA socket.',
    },
    {
      label: 'Autonomous System (ASN)',
      value: `ASN: ${originAssessment.asn || 'AS_UNKNOWN'} (${originAssessment.isp || 'Hosting Provider'}).`,
      detail: 'Network routing prefix matches hosting provider block.',
    },
    {
      label: 'Lookalike Permutation',
      value: domainIntel[0]?.similarity
        ? `Domain ${domainIntel[0].domain} has ${domainIntel[0].similarity.score}% similarity to ${domainIntel[0].similarity.comparedTo}.`
        : 'Domain verified without direct lookalike permutation.',
      detail: 'Calculated via Levenshtein edit distance & homoglyph analysis.',
    },
  ];

  // Inferences generated by the threat scoring engine
  const inferences = [
    {
      label: 'Hosting Architecture',
      value: originAssessment.hostingType === 'DATACENTER'
        ? 'Transmitting server appears cloud/VPS-hosted rather than authentic corporate on-premise mail exchanger.'
        : 'Transmitting server exhibits residential or unknown network profile.',
      confidence: originAssessment.confidence,
    },
    {
      label: 'Threat Pattern Intent',
      value: assessment.classification === 'BUSINESS_EMAIL_COMPROMISE'
        ? 'Executive impersonation and payment urgency indicate targeted BEC wire-fraud attempt.'
        : assessment.classification === 'PHISHING'
        ? 'Lookalike domain combined with credential login endpoint indicates credential harvesting campaign.'
        : 'Statistical behavior aligns with legitimate enterprise communication pattern.',
      confidence: Math.round(assessment.confidence),
    },
  ];

  // Attribution constraints (Strictly distinguishing observed infrastructure from threat actor physical location)
  const attributions = [
    {
      label: 'Attacker Attribution',
      value: analysis.campaignId
        ? `Infrastructure overlap observed with cluster ${analysis.campaignId}. Direct physical actor identity remains unestablished.`
        : 'No direct nation-state or individual threat actor attribution established. Infrastructure may be shared or compromised.',
      status: 'CAUTION',
    },
  ];

  // Supporting evidence points
  const supportingPoints: string[] = [];
  if (authentication.checks.some(c => c.verdict === 'FAIL')) {
    supportingPoints.push('Cryptographic authentication failure (SPF or DMARC policy mismatch)');
  }
  if (analysis.metadata.replyTo && !analysis.metadata.from.includes(analysis.metadata.replyTo)) {
    supportingPoints.push('Reply-To divergence from claimed sender address');
  }
  if (domainIntel.some(d => d.similarity && d.similarity.score > 70)) {
    supportingPoints.push('Lookalike domain impersonating authentic corporate brand');
  }
  if (urls.some(u => u.risk === 'CRITICAL' || u.risk === 'HIGH')) {
    supportingPoints.push('Suspicious or deceptive URL payload endpoint detected');
  }
  if (attachments.some(a => a.risk === 'CRITICAL' || a.risk === 'HIGH')) {
    supportingPoints.push('High-risk static attachment extension or macro pattern');
  }
  if (supportingPoints.length === 0) {
    supportingPoints.push('Standard RFC header formatting and clean domain reputation');
  }

  // Limiting factors & caveats
  const limitingFactors: string[] = [
    'Geolocation represents observed network infrastructure and does not establish physical human location.',
    'Cloud / VPS IP ranges may represent shared multitenant infrastructure.',
    'Attribution is based on digital telemetry and does not imply definitive legal identity.',
  ];

  const confidenceScore = Math.round(assessment.confidence);
  const confidenceStrength = confidenceScore >= 85 ? 'HIGH' : confidenceScore >= 60 ? 'MEDIUM' : 'LOW';
  const confidenceColor = confidenceStrength === 'HIGH' ? '#22c55e' : confidenceStrength === 'MEDIUM' ? '#f59e0b' : '#94a3b8';

  return (
    <div className="panel p-6 border-cyan-500/20 bg-[#080e21] space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-cyan-500/15 pb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-cyan-500/15 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <Shield size={16} />
          </div>
          <div>
            <div className="font-mono text-xs font-bold text-slate-100 uppercase tracking-wider">
              EVIDENCE CONFIDENCE & EPISTEMIC MODEL
            </div>
            <div className="text-[11px] text-slate-400">
              Rigorous separation of Facts, Observations, Inferences, and Attribution
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="text-right font-mono">
            <div className="text-[10px] text-slate-400">EVIDENCE STRENGTH</div>
            <div className="text-xs font-bold" style={{ color: confidenceColor }}>
              {confidenceStrength} ({confidenceScore}% CONFIDENCE)
            </div>
          </div>
        </div>
      </div>

      {/* 4-Tier Forensic Matrix */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Tier 1: FACT */}
        <div className="p-4 rounded-xl bg-[#050a18] border border-cyan-500/20 space-y-3">
          <div className="flex items-center justify-between">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-cyan-950 text-cyan-300 border border-cyan-500/30">
              1. FACT
            </span>
            <span className="text-[10px] font-mono text-slate-500">VERIFIABLE</span>
          </div>
          <div className="text-[11px] text-slate-300 font-sans leading-relaxed">
            Directly observed byte sequences, hashes, and RFC socket records.
          </div>
          <div className="space-y-2 pt-1">
            {facts.map((f, i) => (
              <div key={i} className="p-2 rounded bg-[#080e21] border border-slate-800 text-[11px] font-mono">
                <div className="text-[9px] text-cyan-400 font-bold">{f.label}</div>
                <div className="text-slate-200 mt-0.5 truncate select-all">{f.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Tier 2: OBSERVATION */}
        <div className="p-4 rounded-xl bg-[#050a18] border border-cyan-500/20 space-y-3">
          <div className="flex items-center justify-between">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-sky-950 text-sky-300 border border-sky-500/30">
              2. OBSERVATION
            </span>
            <span className="text-[10px] font-mono text-slate-500">TELEMETRY</span>
          </div>
          <div className="text-[11px] text-slate-300 font-sans leading-relaxed">
            Data resolved from third-party databases, DNS records, and WHOIS tables.
          </div>
          <div className="space-y-2 pt-1">
            {observations.map((o, i) => (
              <div key={i} className="p-2 rounded bg-[#080e21] border border-slate-800 text-[11px] font-mono">
                <div className="text-[9px] text-sky-400 font-bold">{o.label}</div>
                <div className="text-slate-200 mt-0.5">{o.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Tier 3: INFERENCE */}
        <div className="p-4 rounded-xl bg-[#050a18] border border-cyan-500/20 space-y-3">
          <div className="flex items-center justify-between">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-950 text-amber-300 border border-amber-500/30">
              3. INFERENCE
            </span>
            <span className="text-[10px] font-mono text-slate-500">MODEL REASONING</span>
          </div>
          <div className="text-[11px] text-slate-300 font-sans leading-relaxed">
            Hypotheses and behavioral classifications synthesized by the AI/ML model.
          </div>
          <div className="space-y-2 pt-1">
            {inferences.map((inf, i) => (
              <div key={i} className="p-2 rounded bg-[#080e21] border border-slate-800 text-[11px] font-mono">
                <div className="flex justify-between items-center text-[9px] text-amber-400 font-bold">
                  <span>{inf.label}</span>
                  <span>{inf.confidence}% CONF</span>
                </div>
                <div className="text-slate-200 mt-0.5 font-sans leading-snug">{inf.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Tier 4: ATTRIBUTION */}
        <div className="p-4 rounded-xl bg-[#050a18] border border-cyan-500/20 space-y-3">
          <div className="flex items-center justify-between">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-purple-950 text-purple-300 border border-purple-500/30">
              4. ATTRIBUTION
            </span>
            <span className="text-[10px] font-mono text-slate-500">BOUNDED</span>
          </div>
          <div className="text-[11px] text-slate-300 font-sans leading-relaxed">
            Careful correlation of campaign clusters without speculative actor naming.
          </div>
          <div className="space-y-2 pt-1">
            {attributions.map((att, i) => (
              <div key={i} className="p-2 rounded bg-[#080e21] border border-slate-800 text-[11px] font-mono">
                <div className="text-[9px] text-purple-400 font-bold">{att.label}</div>
                <div className="text-slate-200 mt-0.5 font-sans leading-snug">{att.value}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Supporting Evidence vs Limiting Factors */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
        {/* Supporting Evidence */}
        <div className="p-4 rounded-xl bg-[#050a18]/70 border border-emerald-500/20">
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-emerald-400 mb-3">
            <CheckCircle2 size={14} />
            <span>SUPPORTING EVIDENCE ({supportingPoints.length})</span>
          </div>
          <ul className="space-y-1.5 text-xs text-slate-300 font-mono">
            {supportingPoints.map((pt, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">✓</span>
                <span>{pt}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Limiting Factors */}
        <div className="p-4 rounded-xl bg-[#050a18]/70 border border-amber-500/20">
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-amber-400 mb-3">
            <AlertTriangle size={14} />
            <span>LIMITING FACTORS & CAVEATS ({limitingFactors.length})</span>
          </div>
          <ul className="space-y-1.5 text-xs text-slate-300 font-mono">
            {limitingFactors.map((lim, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="text-amber-400 font-bold">⚠</span>
                <span>{lim}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
